[workspace]
members = ["planner_registry", "planner_lib", "planner_ui/@rsw/planner_lib_wasm"]

[workspace.dependencies]
planner_registry = { path = "./planner_registry" }
planner_lib = { path = "./planner_lib" }