[package]
name = "planner_lib"
version = "0.1.0"
authors = ["funlennysub", "localcc <work@localcc.cc>"]
license = "MIT"
license-file = "LICENSE"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
